nombre=input("Ingrese su nombre:")
print("Primer caracter")
print(nombre[0])
print("Cantidad de letras del nombre:")
print(len(nombre))
apellido=input("Ingrese su apellido:")
print("Primer caracter de su apellido")
print(apellido[0])
print("Cantidad de letras del apellido:")
print(len(apellido))